#### Strategy Outline

This notebook tests 3 strategies. **Live sleeve: strategy 3 (50-day MA).**

1) COT 80/20 **cross** (no RSI)
- Long on Commercial Index cross of 80; short on cross of 20
- Stop 1×ATR, target 3×ATR, time stop after N days

2) COT + RSI **zone** (no MA)
- Long: Commercial ≥ 80 and RSI < 30; short: ≤ 20 and RSI > 70
- Fill at signal-day **close**
- Stop 1×ATR, target 4×ATR, RSI exit 60, max hold 20
- 1% of current $30k book

3) COT + RSI + **50-day MA** (heatmap winner) — **the strategy to trade**
- Same COT+RSI entry as (2)
- Long only if Close > MA50; short only if Close < MA50
- Fill at **next day's open**
- Stop 1×ATR, target 4×ATR, RSI exit 60, max hold 20

In [2]:
import pandas as pd

#### STRATEGY 1 COT 80/20

In [3]:
from backtest_engine.data import load_cot_data, prepare_base_data
from backtest_engine.indicators import add_standard_indicators
from backtest_engine.backtester import run_backtest
from backtest_engine.metrics import calculate_performance_metrics
from backtest_engine.stops import ATRStopTarget

cot = load_cot_data()
markets = sorted(
    cot.loc[cot["data_type"] == "daily_price", "Market"].unique()
)

stop = ATRStopTarget(atr_stop_mult=1, atr_target_mult=3, max_hold_days=7)

rows = []
all_trades = []

for market in markets:
    df = prepare_base_data(cot, market)
    if df.empty or "Commercial_Index" not in df.columns:
        continue
    df = add_standard_indicators(df)

    ci = df["Commercial_Index"]
    df["signal"] = 0
    df.loc[(ci >= 80) & (ci.shift(1) < 80), "signal"] = 1
    df.loc[(ci <= 20) & (ci.shift(1) > 20), "signal"] = -1
    df["entry_price"] = df["Close"]

    res = run_backtest(df, market, stop)
    m = calculate_performance_metrics(res["trades"], res["equity_curve"])
    missed = 0 if res["missed_trades"].empty else len(res["missed_trades"])

    rows.append({
        "Market": market,
        "Trades": m["total_trades"],
        "Missed": missed,
        "Win Rate %": round(m["win_rate"], 1),
        "Return %": round(m["total_return_pct"], 2),
        "CAGR %": round(m["cagr"], 2),
        "Max DD %": round(m["max_drawdown_pct"], 2),
        "Sharpe": round(m["sharpe_ratio"], 2),
        "Profit Factor": round(min(m["profit_factor"], 999), 2),
        "Net Profit": round(m["net_profit"], 2),
    })
    if not res["trades"].empty:
        all_trades.append(res["trades"])

summary = pd.DataFrame(rows).sort_values("Net Profit", ascending=False)
summary = summary[summary["Market"] != "*** TOTAL ***"]

trades = pd.concat(all_trades, ignore_index=True) if all_trades else pd.DataFrame()

INITIAL = 30_000
n_books = len(summary)

t = trades.sort_values("exit_date") if not trades.empty else trades
eq = [INITIAL]
for pnl in t["pnl"]:
    eq.append(eq[-1] + pnl)

m = calculate_performance_metrics(t, eq, INITIAL)
total = {
    "Market": "*** TOTAL ***",
    "Trades": m["total_trades"],
    "Missed": int(summary["Missed"].sum()),
    "Win Rate %": round(m["win_rate"], 1),
    "Return %": round(m["net_profit"] / (INITIAL * n_books) * 100, 2),
    "CAGR %": round(m["cagr"], 2),
    "Max DD %": round(m["max_drawdown_pct"], 2),
    "Sharpe": round(m["sharpe_ratio"], 2),
    "Profit Factor": round(min(m["profit_factor"], 999), 2),
    "Net Profit": round(m["net_profit"], 2),
}
summary = pd.concat([summary, pd.DataFrame([total])], ignore_index=True)
summary

,Market,Trades,Missed,Win Rate %,Return %,CAGR %,Max DD %,Sharpe,Profit Factor,Net Profit
0,E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE,3,3,66.7,6.19,16.97,0.65,2.11,10.54,1858.00
1,CORN - CHICAGO BOARD OF TRADE,9,0,55.6,5.68,1.90,1.81,0.60,2.50,1704.75
2,BITCOIN - CHICAGO MERCANTILE EXCHANGE,6,0,50.0,4.64,2.57,1.00,0.70,2.49,1392.17
3,BRAZILIAN REAL - CHICAGO MERCANTILE EXCHANGE,7,0,57.1,3.48,2.19,1.76,0.57,2.31,1043.50
4,MICRO BITCOIN - CHICAGO MERCANTILE EXCHANGE,4,0,50.0,3.11,2.42,1.00,0.62,2.53,931.80
5,EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTI...,2,0,50.0,2.08,2.99,0.76,0.67,3.66,623.62
6,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,3,0,33.3,1.72,2.79,0.97,0.75,2.29,514.80
7,WTI-PHYSICAL - NEW YORK MERCANTILE EXCHANGE,3,0,33.3,1.58,1.84,1.41,0.49,2.13,475.30
8,BRITISH POUND - CHICAGO MERCANTILE EXCHANGE,5,0,40.0,1.22,1.70,1.32,0.35,1.66,365.75
9,SOYBEAN OIL - CHICAGO BOARD OF TRADE,11,0,45.5,0.47,0.17,3.35,0.04,1.09,141.84
10,COPPER- #1 - COMMODITY EXCHANGE INC.,1,3,100.0,0.22,9.18,0.00,0.00,999.00,65.00
11,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,3,0,66.7,0.18,0.26,0.90,-0.33,1.20,53.20
12,COFFEE C - ICE FUTURES U.S.,0,1,0.0,0.00,0.00,0.00,0.00,0.00,0.00
13,MICRO GOLD - COMMODITY EXCHANGE INC.,0,1,0.0,0.00,0.00,0.00,0.00,0.00,0.00
14,SWISS FRANC - CHICAGO MERCANTILE EXCHANGE,0,3,0.0,0.00,0.00,0.00,0.00,0.00,0.00
15,SO AFRICAN RAND - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
16,UST 10Y NOTE - CHICAGO BOARD OF TRADE,0,4,0.0,0.00,0.00,0.00,0.00,0.00,0.00
17,PLATINUM - NEW YORK MERCANTILE EXCHANGE,0,2,0.0,0.00,0.00,0.00,0.00,0.00,0.00
18,PALLADIUM - NEW YORK MERCANTILE EXCHANGE,0,1,0.0,0.00,0.00,0.00,0.00,0.00,0.00
19,OATS - CHICAGO BOARD OF TRADE,0,3,0.0,0.00,0.00,0.00,0.00,0.00,0.00
20,UST BOND - CHICAGO BOARD OF TRADE,0,7,0.0,0.00,0.00,0.00,0.00,0.00,0.00
21,NEW ZEALAND DOLLAR - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
22,COTTON NO. 2 - ICE FUTURES U.S.,0,10,0.0,0.00,0.00,0.00,0.00,0.00,0.00
23,VIX FUTURES - CBOE FUTURES EXCHANGE,0,6,0.0,0.00,0.00,0.00,0.00,0.00,0.00
24,MICRO SILVER - COMMODITY EXCHANGE INC.,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
25,E-MINI NATURAL GAS - NEW YORK MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
26,EMINI RUSSELL 1000 GROWTH - CHICAGO MERCANTILE...,0,1,0.0,0.00,0.00,0.00,0.00,0.00,0.00
27,SUGAR NO. 11 - ICE FUTURES U.S.,0,4,0.0,0.00,0.00,0.00,0.00,0.00,0.00
28,MICRO COPPER - COMMODITY EXCHANGE INC.,0,1,0.0,0.00,0.00,0.00,0.00,0.00,0.00
29,WHEAT-SRW - CHICAGO BOARD OF TRADE,0,8,0.0,0.00,0.00,0.00,0.00,0.00,0.00
30,LIVE CATTLE - CHICAGO MERCANTILE EXCHANGE,0,11,0.0,0.00,0.00,0.00,0.00,0.00,0.00
31,LEAN HOGS - CHICAGO MERCANTILE EXCHANGE,0,7,0.0,0.00,0.00,0.00,0.00,0.00,0.00
32,GOLD - COMMODITY EXCHANGE INC.,0,7,0.0,0.00,0.00,0.00,0.00,0.00,0.00
33,GASOLINE RBOB - NEW YORK MERCANTILE EXCHANGE,0,5,0.0,0.00,0.00,0.00,0.00,0.00,0.00
34,FEEDER CATTLE - CHICAGO MERCANTILE EXCHANGE,0,4,0.0,0.00,0.00,0.00,0.00,0.00,0.00
35,COCOA - ICE FUTURES U.S.,0,3,0.0,0.00,0.00,0.00,0.00,0.00,0.00
36,MICRO E-MINI NASDAQ-100 INDEX - CHICAGO MERCAN...,0,6,0.0,0.00,0.00,0.00,0.00,0.00,0.00
37,JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE,2,0,50.0,-0.03,-0.11,0.92,1.00,0.97,-9.44
38,MICRO ETHER - CHICAGO MERCANTILE EXCHANGE,4,0,50.0,-0.44,-0.29,1.99,-0.21,0.78,-133.44
39,MINI SOYBEANS - CHICAGO BOARD OF TRADE,2,0,50.0,-0.48,-0.27,0.67,-0.51,0.28,-145.50
40,NAT GAS NYME - NEW YORK MERCANTILE EXCHANGE,1,6,0.0,-0.51,-18.68,0.51,0.00,0.00,-152.50
41,RUSSELL E-MINI - CHICAGO MERCANTILE EXCHANGE,1,0,0.0,-0.72,-35.44,0.72,0.00,0.00,-214.85
42,NIKKEI STOCK AVERAGE - CHICAGO MERCANTILE EXCH...,1,1,0.0,-0.72,-51.41,0.72,0.00,0.00,-215.75
43,UST 2Y NOTE - CHICAGO BOARD OF TRADE,1,0,0.0,-0.85,-57.59,0.85,0.00,0.00,-256.25
44,UST 5Y NOTE - CHICAGO BOARD OF TRADE,1,1,0.0,-0.99,-63.11,0.99,0.00,0.00,-297.66
45,SOYBEANS - CHICAGO BOARD OF TRADE,8,0,37.5,-1.20,-0.47,2.66,-0.06,0.73,-359.00
46,SOYBEAN MEAL - CHICAGO BOARD OF TRADE,8,0,37.5,-1.49,-0.57,3.51,-0.25,0.58,-446.40
47,MEXICAN PESO - CHICAGO MERCANTILE EXCHANGE,2,0,0.0,-1.78,-32.04,1.78,-22.63,0.00,-534.50
48,*** TOTAL ***,88,109,44.3,0.44,6.65,7.38,0.68,1.52,6404.44

In [4]:
# Analayis of holding period (remembering ATR is set as a profit target)
import pandas as pd
import plotly.graph_objects as go

# Build signal data once
prepared = {}
for market in markets:
    df = prepare_base_data(cot, market)
    if df.empty or "Commercial_Index" not in df.columns:
        continue
    df = add_standard_indicators(df)
    ci = df["Commercial_Index"]
    df["signal"] = 0
    df.loc[(ci >= 80) & (ci.shift(1) < 80), "signal"] = 1
    df.loc[(ci <= 20) & (ci.shift(1) > 20), "signal"] = -1
    df["entry_price"] = df["Close"]
    prepared[market] = df

holds = list(range(2, 31))
pnl_by_hold = []

for hold in holds:
    stop = ATRStopTarget(atr_stop_mult=1, atr_target_mult=3, max_hold_days=hold)
    total_pnl = 0.0
    for market, df in prepared.items():
        res = run_backtest(df, market, stop)
        if not res["trades"].empty:
            total_pnl += res["trades"]["pnl"].sum()
    pnl_by_hold.append(total_pnl)

hold_df = pd.DataFrame({"max_hold_days": holds, "net_profit": pnl_by_hold})

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=hold_df["max_hold_days"],
    y=hold_df["net_profit"],
    mode="lines+markers",
    name="Net profit",
))
fig.update_layout(
    title="COT 80/20 cross — net P&amp;L vs max hold (days)",
    xaxis_title="Max hold (days)",
    yaxis_title="Total profit / loss ($)",
    xaxis=dict(dtick=2, range=[2, 30]),
    template="plotly_dark",
)
fig.show()
hold_df

    max_hold_days  net_profit
0               2     3703.50
1               3     1825.90
2               4     1793.49
3               5     2980.02
4               6     5139.47
5               7     6404.44
6               8     4431.25
7               9     4736.94
8              10     4606.12
9              11     4182.93
10             12     5921.55
11             13     4745.98
12             14     4099.87
13             15     4393.53
14             16     4554.01
15             17     4773.85
16             18     5289.31
17             19     5155.31
18             20     4788.31
19             21     4377.51
20             22     4677.01
21             23     4612.01
22             24     4729.51
23             25     4652.01
24             26     4782.01
25             27     4929.76
26             28     4929.76
27             29     4929.76
28             30     4929.76

In [5]:
print(trades["entry_date"].min(), "→", trades["exit_date"].max())
print((trades["exit_date"].max() - trades["entry_date"].min()).days / 365.25, "years")

2023-09-19 00:00:00 → 2026-09-21 00:00:00
3.0061601642710474 years

#### Strategy 2 - COT + RSI. 

##### only long when 80/20 in favor and RSI is overbought for shorts, or oversold for longs

In [6]:
from backtest_engine.data import load_cot_data as load_data
from backtest_engine.indicators import calculate_atr
from backtest_engine.metrics import calculate_performance_metrics
from backtest_engine.cot_rsi import (
    prepare_strategy_data, generate_signals, COTRSIBacktester,
)
import pandas as pd
import plotly.express as px

raw = load_data()
markets = sorted(raw.loc[raw["data_type"] == "daily_price", "Market"].unique())

prepared = {}
for market in markets:
    df = prepare_strategy_data(raw, market, start_date="2023-01-01")
    if df.empty:
        continue
    df = generate_signals(calculate_atr(df, period=10))
    prepared[market] = df

holds = [5, 7, 10, 15, 20, 30]   # refine later with range(2, 31)
targets = [2, 3, 4, 5]

rows = []
for hold in holds:
    for tgt in targets:
        total_pnl = 0.0
        n_trades = 0
        for market, df in prepared.items():
            bt = COTRSIBacktester(
                initial_capital=30000,
                risk_per_trade=0.01,
                atr_stop_mult=1,
                atr_target_mult=tgt,
                max_hold_days=hold,
                rsi_exit=60,
            )
            res = bt.backtest(df, market_name=market)
            if not res["trades"].empty:
                total_pnl += res["trades"]["pnl"].sum()
                n_trades += len(res["trades"])
        rows.append({
            "max_hold_days": hold,
            "atr_target_mult": tgt,
            "net_profit": total_pnl,
            "trades": n_trades,
        })

grid = pd.DataFrame(rows)
pivot = grid.pivot(index="atr_target_mult", columns="max_hold_days", values="net_profit")
px.imshow(pivot, text_auto=".0f", aspect="auto",
          labels=dict(x="Max hold (days)", y="ATR target", color="Net P&L"),
          title="COT+RSI — net P&L vs hold × ATR target (stop=2×ATR)").show()
grid.sort_values("net_profit", ascending=False).head(10)

Pre-computing backtest results for all markets...
Computed results for 46 markets

🔔 Checking for recent signals...
⚠️  ALERT: 16 signal(s) in the last 7 days!
   LONG - COCOA - ICE FUTURES U.S. on 2026-09-18 (COT: 81.9, RSI: 15.0)
   LONG - LEAN HOGS - CHICAGO MERCANTILE EXCHANGE on 2026-09-18 (COT: 100.0, RSI: 22.8)
   LONG - COCOA - ICE FUTURES U.S. on 2026-09-17 (COT: 81.9, RSI: 21.0)
   LONG - LEAN HOGS - CHICAGO MERCANTILE EXCHANGE on 2026-09-17 (COT: 100.0, RSI: 24.0)
   SHORT - SOYBEAN MEAL - CHICAGO BOARD OF TRADE on 2026-09-17 (COT: 0.0, RSI: 76.3)
   LONG - COCOA - ICE FUTURES U.S. on 2026-09-16 (COT: 81.9, RSI: 19.0)
   LONG - LEAN HOGS - CHICAGO MERCANTILE EXCHANGE on 2026-09-16 (COT: 100.0, RSI: 23.2)
   LONG - UST BOND - CHICAGO BOARD OF TRADE on 2026-09-16 (COT: 82.3, RSI: 27.6)
   LONG - COCOA - ICE FUTURES U.S. on 2026-09-15 (COT: 81.9, RSI: 11.4)
   SHORT - JAPANESE YEN - CHICAGO MERCANTILE EXCHAN on 2026-09-15 (COT: 19.5, RSI: 72.0)
   LONG - LEAN HOGS - CHICAGO MERCANTILE EXCHANGE on 2026-09-15 (COT: 100.0, RSI: 24.2)
   SHORT - SOYBEAN MEAL - CHICAGO BOARD OF TRADE on 2026-09-15 (COT: 0.0, RSI: 72.0)
   LONG - UST BOND - CHICAGO BOARD OF TRADE on 2026-09-15 (COT: 82.3, RSI: 20.7)
   LONG - COCOA - ICE FUTURES U.S. on 2026-09-14 (COT: 81.7, RSI: 24.1)
   LONG - UST 10Y NOTE - CHICAGO BOARD OF TRADE on 2026-09-14 (COT: 80.9, RSI: 14.4)
   LONG - UST BOND - CHICAGO BOARD OF TRADE on 2026-09-14 (COT: 81.4, RSI: 19.8)

    max_hold_days  atr_target_mult   net_profit  trades
2               5                4  9866.716667     653
18             20                4  9670.460068     591
3               5                5  9590.116682     653
22             30                4  8612.126068     591
10             10                4  8545.472130     594
14             15                4  8460.137968     591
1               5                3  8263.159027     653
6               7                4  8036.184358     611
19             20                5  7858.856584     591
7               7                5  7820.244373     611

In [7]:
from backtest_engine.data import load_cot_data as load_data
from backtest_engine.indicators import calculate_atr
from backtest_engine.cot_rsi import (
    prepare_strategy_data, generate_signals, COTRSIBacktester,
)
from backtest_engine.metrics import calculate_performance_metrics
import pandas as pd

RSI_STOP_MULT = 1      # ATR stop  ← change this
RSI_TARGET_MULT = 4    # ATR profit target
RSI_MAX_HOLD = 20
RSI_EXIT = 60
RSI_INITIAL = 30_000

RSI_raw = load_data()
RSI_markets = sorted(
    RSI_raw.loc[RSI_raw["data_type"] == "daily_price", "Market"].unique()
)

RSI_rows = []
RSI_all_trades = []

for market in RSI_markets:
    df = prepare_strategy_data(RSI_raw, market)
    if df.empty:
        continue
    df = generate_signals(calculate_atr(df, period=10))

    RSI_bt = COTRSIBacktester(
        initial_capital=RSI_INITIAL,
        risk_per_trade=0.01,
        atr_stop_mult=RSI_STOP_MULT,
        atr_target_mult=RSI_TARGET_MULT,
        max_hold_days=RSI_MAX_HOLD,
        rsi_exit=RSI_EXIT,
    )
    res = RSI_bt.backtest(df, market_name=market)
    RSI_m = calculate_performance_metrics(res["trades"], res["equity_curve"], RSI_INITIAL)
    RSI_missed = 0 if res["missed_trades"].empty else len(res["missed_trades"])

    RSI_rows.append({
        "Market": market,
        "Trades": RSI_m["total_trades"],
        "Missed": RSI_missed,
        "Win Rate %": round(RSI_m["win_rate"], 1),
        "Return %": round(RSI_m["total_return_pct"], 2),
        "CAGR %": round(RSI_m["cagr"], 2),
        "Max DD %": round(RSI_m["max_drawdown_pct"], 2),
        "Sharpe": round(RSI_m["sharpe_ratio"], 2),
        "Profit Factor": round(min(RSI_m["profit_factor"], 999), 2),
        "Net Profit": round(RSI_m["net_profit"], 2),
    })
    if not res["trades"].empty:
        RSI_all_trades.append(res["trades"])

RSI_summary = pd.DataFrame(RSI_rows).sort_values("Net Profit", ascending=False)
RSI_summary = RSI_summary[RSI_summary["Market"] != "*** TOTAL ***"]

RSI_trades = (
    pd.concat(RSI_all_trades, ignore_index=True) if RSI_all_trades else pd.DataFrame()
)

RSI_n_books = len(RSI_summary)
RSI_t = RSI_trades.sort_values("exit_date") if not RSI_trades.empty else RSI_trades
RSI_eq = [RSI_INITIAL]
for pnl in RSI_t["pnl"]:
    RSI_eq.append(RSI_eq[-1] + pnl)

RSI_m = calculate_performance_metrics(RSI_t, RSI_eq, RSI_INITIAL)
RSI_total = {
    "Market": "*** TOTAL ***",
    "Trades": RSI_m["total_trades"],
    "Missed": int(RSI_summary["Missed"].sum()),
    "Win Rate %": round(RSI_m["win_rate"], 1),
    "Return %": round(RSI_m["net_profit"] / (RSI_INITIAL * RSI_n_books) * 100, 2),
    "CAGR %": round(RSI_m["cagr"], 2),
    "Max DD %": round(RSI_m["max_drawdown_pct"], 2),
    "Sharpe": round(RSI_m["sharpe_ratio"], 2),
    "Profit Factor": round(min(RSI_m["profit_factor"], 999), 2),
    "Net Profit": round(RSI_m["net_profit"], 2),
}
RSI_summary = pd.concat([RSI_summary, pd.DataFrame([RSI_total])], ignore_index=True)
RSI_summary

,Market,Trades,Missed,Win Rate %,Return %,CAGR %,Max DD %,Sharpe,Profit Factor,Net Profit
0,COTTON NO. 2 - ICE FUTURES U.S.,37,0,45.9,14.74,5.63,5.26,1.07,1.77,4420.64
1,BITCOIN - CHICAGO MERCANTILE EXCHANGE,5,0,80.0,11.16,9.89,0.04,2.97,268.45,3348.44
2,VIX FUTURES - CBOE FUTURES EXCHANGE,6,0,50.0,9.00,9.14,2.00,1.52,4.00,2700.64
3,UST 5Y NOTE - CHICAGO BOARD OF TRADE,7,0,85.7,8.57,14.28,0.96,4.69,9.57,2571.03
4,LIVE CATTLE - CHICAGO MERCANTILE EXCHANGE,22,0,50.0,8.08,4.77,3.17,0.87,1.73,2422.97
5,NAT GAS NYME - NEW YORK MERCANTILE EXCHANGE,9,0,66.7,7.87,4.87,1.00,0.98,3.62,2359.57
6,COPPER- #1 - COMMODITY EXCHANGE INC.,6,0,66.7,7.82,12.41,2.00,1.93,4.91,2344.89
7,SOYBEAN MEAL - CHICAGO BOARD OF TRADE,26,0,42.3,6.42,2.43,6.55,0.63,1.44,1925.68
8,MICRO COPPER - COMMODITY EXCHANGE INC.,6,0,66.7,5.64,13.34,2.00,1.94,3.82,1691.42
9,SOYBEAN OIL - CHICAGO BOARD OF TRADE,20,0,45.0,5.48,2.21,3.00,0.43,1.50,1643.48
10,BRITISH POUND - CHICAGO MERCANTILE EXCHANGE,4,0,75.0,5.04,12.28,1.00,2.24,6.04,1511.90
11,BRAZILIAN REAL - CHICAGO MERCANTILE EXCHANGE,7,0,71.4,4.26,3.14,0.98,0.97,3.13,1278.07
12,WTI-PHYSICAL - NEW YORK MERCANTILE EXCHANGE,5,0,60.0,3.46,16.38,1.00,1.92,2.73,1039.07
13,NIKKEI STOCK AVERAGE - CHICAGO MERCANTILE EXCH...,2,58,50.0,3.22,13.43,0.69,1.39,5.51,967.50
14,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,2,0,100.0,3.10,4.64,0.00,2.26,999.00,931.49
15,SWISS FRANC - CHICAGO MERCANTILE EXCHANGE,7,0,42.9,3.05,2.02,2.00,0.03,1.76,914.86
16,SUGAR NO. 11 - ICE FUTURES U.S.,6,0,50.0,2.75,5.23,2.00,0.98,1.92,824.11
17,MICRO ETHER - CHICAGO MERCANTILE EXCHANGE,26,0,38.5,2.50,1.77,5.82,0.46,1.16,750.25
18,E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE,4,0,75.0,2.38,1.29,0.08,1.81,30.80,715.25
19,WHEAT-SRW - CHICAGO BOARD OF TRADE,7,0,42.9,2.12,1.47,1.99,0.72,1.53,635.50
20,EMINI RUSSELL 1000 GROWTH - CHICAGO MERCANTILE...,24,0,41.7,1.94,1.47,2.38,-0.02,1.16,582.00
21,FEEDER CATTLE - CHICAGO MERCANTILE EXCHANGE,13,0,38.5,1.62,1.29,5.90,0.26,1.20,486.58
22,OATS - CHICAGO BOARD OF TRADE,2,0,50.0,1.27,33.43,0.99,1.07,2.29,381.45
23,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,5,0,60.0,0.93,1.22,1.97,-0.03,1.47,279.19
24,PLATINUM - NEW YORK MERCANTILE EXCHANGE,1,0,100.0,0.85,47.42,0.00,0.00,999.00,256.10
25,EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTI...,8,0,37.5,0.57,1.51,4.08,0.48,1.14,172.46
26,SO AFRICAN RAND - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
27,MICRO E-MINI NASDAQ-100 INDEX - CHICAGO MERCAN...,9,10,33.3,-0.14,-0.43,4.85,-0.12,0.97,-41.95
28,RUSSELL E-MINI - CHICAGO MERCANTILE EXCHANGE,3,0,33.3,-0.52,-12.78,1.92,-0.97,0.73,-156.82
29,PALLADIUM - NEW YORK MERCANTILE EXCHANGE,15,0,33.3,-0.72,-1.39,5.87,0.44,0.92,-217.25
30,MICRO SILVER - COMMODITY EXCHANGE INC.,10,0,30.0,-1.04,-1.97,2.94,-0.52,0.84,-311.56
31,JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE,8,0,25.0,-1.08,-3.60,6.00,0.49,0.82,-323.74
32,LEAN HOGS - CHICAGO MERCANTILE EXCHANGE,29,0,34.5,-1.54,-0.86,5.51,-0.09,0.92,-460.77
33,MINI SOYBEANS - CHICAGO BOARD OF TRADE,29,0,31.0,-1.67,-0.87,7.96,-0.18,0.92,-502.33
34,UST 10Y NOTE - CHICAGO BOARD OF TRADE,4,0,25.0,-1.96,-12.52,2.97,-2.78,0.35,-587.66
35,SOYBEANS - CHICAGO BOARD OF TRADE,25,0,28.0,-2.99,-1.17,5.95,-0.37,0.83,-897.25
36,UST BOND - CHICAGO BOARD OF TRADE,6,0,33.3,-3.18,-3.49,3.98,-1.72,0.21,-952.52
37,MICRO BITCOIN - CHICAGO MERCANTILE EXCHANGE,5,0,20.0,-3.23,-42.00,4.00,-5.02,0.19,-968.44
38,CORN - CHICAGO BOARD OF TRADE,25,0,28.0,-3.43,-1.25,8.89,-0.15,0.80,-1027.78
39,COCOA - ICE FUTURES U.S.,11,18,27.3,-2.57,-3.07,3.23,-0.96,0.48,-1067.30
40,MEXICAN PESO - CHICAGO MERCANTILE EXCHANGE,11,0,18.2,-5.59,-30.37,7.06,-3.71,0.38,-1675.57
41,COFFEE C - ICE FUTURES U.S.,9,0,11.1,-5.69,-53.43,8.02,-4.85,0.29,-1706.95
42,GASOLINE RBOB - NEW YORK MERCANTILE EXCHANGE,10,0,20.0,-5.77,-5.59,7.83,-2.31,0.28,-1729.76
43,UST 2Y NOTE - CHICAGO BOARD OF TRADE,7,0,0.0,-7.00,-27.62,7.00,-67.91,0.00,-2099.93
44,GOLD - COMMODITY EXCHANGE INC.,26,0,19.2,-15.80,-10.59,17.61,-3.23,0.24,-4740.52
45,MICRO GOLD - COMMODITY EXCHANGE INC.,82,0,29.3,-26.72,-10.10,27.91,-1.23,0.54,-8015.99
46,*** TOTAL ***,591,86,37.6,0.70,10.00,28.29,0.71,1.09,9670.46

##### Alerts for RSI strategy

In [8]:
from datetime import datetime, timedelta
from backtest_engine.data import load_cot_data as load_data
from backtest_engine.indicators import calculate_atr
from backtest_engine.cot_rsi import prepare_strategy_data, generate_signals
import pandas as pd

RSI_STOP_MULT = 1
RSI_TARGET_MULT = 4
RSI_LOOKBACK_DAYS = 31
RSI_ALERT_N = 4

raw = load_data()
markets = sorted(raw.loc[raw["data_type"] == "daily_price", "Market"].unique())
cutoff = pd.Timestamp(datetime.now() - timedelta(days=RSI_LOOKBACK_DAYS))

rsi_alerts = []

for market in markets:
    df = prepare_strategy_data(raw, market)
    if df.empty:
        continue
    df = generate_signals(calculate_atr(df, period=10))
    hit = df[(df["signal"] != 0) & df["ATR"].notna() & (df["Date"] >= cutoff)]

    for _, row in hit.iterrows():
        entry = float(row["Close"])
        atr = float(row["ATR"])
        long = row["signal"] == 1
        stop = entry - RSI_STOP_MULT * atr if long else entry + RSI_STOP_MULT * atr
        target = entry + RSI_TARGET_MULT * atr if long else entry - RSI_TARGET_MULT * atr
        rsi_alerts.append({
            "Market": market,
            "Signal date": row["Date"],
            "Fill": "close (same day)",
            "Signal": "LONG" if long else "SHORT",
            "Entry": round(entry, 4),
            "ATR": round(atr, 4),
            "Stop (1×ATR)": round(stop, 4),
            "Target (4×ATR)": round(target, 4),
            "Commercial_Index": round(float(row["Commercial_Index"]), 1),
            "RSI": round(float(row["RSI"]), 1),
        })

RSI_ALERTS = pd.DataFrame(rsi_alerts)
print(f"Raw alerts in last {RSI_LOOKBACK_DAYS} days: {len(RSI_ALERTS)}")
if not RSI_ALERTS.empty:
    RSI_ALERTS = RSI_ALERTS.sort_values("Signal date", ascending=False).head(RSI_ALERT_N)
display(RSI_ALERTS)

Raw alerts in last 31 days: 93

,Market,Signal date,Fill,Signal,Entry,ATR,Stop (1×ATR),Target (4×ATR),Commercial_Index,RSI
32,LEAN HOGS - CHICAGO MERCANTILE EXCHANGE,2026-09-18,close (same day),LONG,78.1,1.4825,76.6175,84.03,100.0,22.8
5,COCOA - ICE FUTURES U.S.,2026-09-18,close (same day),LONG,5327.0,316.3000,5010.7000,6592.20,81.9,15.0
4,COCOA - ICE FUTURES U.S.,2026-09-17,close (same day),LONG,5772.0,297.5000,5474.5000,6962.00,81.9,21.0
64,SOYBEAN MEAL - CHICAGO BOARD OF TRADE,2026-09-17,close (same day),SHORT,371.3,8.2700,379.5700,338.22,0.0,76.3

#### Strategy 3 — 50-day MA filter (heatmap winner)

COT+RSI zone, long only if Close > MA50, short only if Close < MA50, fill next open.

In [9]:
from backtest_engine.data import load_cot_data as load_data
from backtest_engine.indicators import calculate_atr
from backtest_engine.cot_rsi import (
    prepare_strategy_data, generate_signals, COTRSIBacktester,
)
from backtest_engine.metrics import calculate_performance_metrics
import pandas as pd
import numpy as np

RSI_EXIT = 60
MA_PERIOD = 50          # heatmap winner
MA_STOP_MULT = 1
MA_TARGET_MULT = 4
MA_MAX_HOLD = 20
MA_INITIAL = 30000

def MA_backtest_next_open(df, market):
    """Enter at Open on bars where signal != 0 (signal already shifted to fill day)."""
    df = df.copy()
    fill = df["signal"] != 0
    close_real = df["Close"].copy()
    df.loc[fill, "Close"] = df.loc[fill, "Open"]
    bt = COTRSIBacktester(
        initial_capital=MA_INITIAL,
        risk_per_trade=0.01,
        atr_stop_mult=MA_STOP_MULT,
        atr_target_mult=MA_TARGET_MULT,
        max_hold_days=MA_MAX_HOLD,
        rsi_exit=RSI_EXIT,
    )
    res = bt.backtest(df, market_name=market)
    df["Close"] = close_real
    return res

MA_raw = load_data()
MA_markets = sorted(
    MA_raw.loc[MA_raw["data_type"] == "daily_price", "Market"].unique()
)

MA_rows = []
MA_all_trades = []

for market in MA_markets:
    df = prepare_strategy_data(MA_raw, market)
    if df.empty:
        continue
    df = generate_signals(calculate_atr(df, period=10))
    df["MA"] = df["Close"].rolling(MA_PERIOD).mean()

    df.loc[(df["signal"] == 1) & ~(df["Close"] > df["MA"]), "signal"] = 0
    df.loc[(df["signal"] == -1) & ~(df["Close"] < df["MA"]), "signal"] = 0

    df["signal"] = df["signal"].shift(1).fillna(0).astype(int)

    res = MA_backtest_next_open(df, market)
    MA_m = calculate_performance_metrics(res["trades"], res["equity_curve"], MA_INITIAL)
    MA_missed = 0 if res["missed_trades"].empty else len(res["missed_trades"])

    MA_rows.append({
        "Market": market,
        "Trades": MA_m["total_trades"],
        "Missed": MA_missed,
        "Win Rate %": round(MA_m["win_rate"], 1),
        "Return %": round(MA_m["total_return_pct"], 2),
        "CAGR %": round(MA_m["cagr"], 2),
        "Max DD %": round(MA_m["max_drawdown_pct"], 2),
        "Sharpe": round(MA_m["sharpe_ratio"], 2),
        "Profit Factor": round(min(MA_m["profit_factor"], 999), 2),
        "Net Profit": round(MA_m["net_profit"], 2),
    })
    if not res["trades"].empty:
        MA_all_trades.append(res["trades"])

MA_summary = pd.DataFrame(MA_rows).sort_values("Net Profit", ascending=False)
MA_summary = MA_summary[MA_summary["Market"] != "*** TOTAL ***"]
MA_trades = (
    pd.concat(MA_all_trades, ignore_index=True) if MA_all_trades else pd.DataFrame()
)

MA_n_books = len(MA_summary)
MA_t = MA_trades.sort_values("exit_date") if not MA_trades.empty else MA_trades
MA_eq = [MA_INITIAL]
for pnl in MA_t["pnl"]:
    MA_eq.append(MA_eq[-1] + pnl)

MA_m = calculate_performance_metrics(MA_t, MA_eq, MA_INITIAL)
MA_total = {
    "Market": "*** TOTAL ***",
    "Trades": MA_m["total_trades"],
    "Missed": int(MA_summary["Missed"].sum()),
    "Win Rate %": round(MA_m["win_rate"], 1),
    "Return %": round(MA_m["net_profit"] / (MA_INITIAL * MA_n_books) * 100, 2),
    "CAGR %": round(MA_m["cagr"], 2),
    "Max DD %": round(MA_m["max_drawdown_pct"], 2),
    "Sharpe": round(MA_m["sharpe_ratio"], 2),
    "Profit Factor": round(min(MA_m["profit_factor"], 999), 2),
    "Net Profit": round(MA_m["net_profit"], 2),
}
MA_summary = pd.concat([MA_summary, pd.DataFrame([MA_total])], ignore_index=True)
MA_summary

,Market,Trades,Missed,Win Rate %,Return %,CAGR %,Max DD %,Sharpe,Profit Factor,Net Profit
0,NIKKEI STOCK AVERAGE - CHICAGO MERCANTILE EXCH...,2,6,100.0,5.33,2255.17,0.00,17.07,999.00,1598.00
1,MICRO COPPER - COMMODITY EXCHANGE INC.,2,0,100.0,5.08,16.75,0.00,9.71,999.00,1525.43
2,SWISS FRANC - CHICAGO MERCANTILE EXCHANGE,1,0,100.0,4.00,4950.48,0.00,0.00,999.00,1200.00
3,BITCOIN - CHICAGO MERCANTILE EXCHANGE,4,0,50.0,3.88,3.46,1.00,0.89,3.69,1163.45
4,MICRO ETHER - CHICAGO MERCANTILE EXCHANGE,1,0,100.0,2.01,83.49,0.00,0.00,999.00,604.25
5,UST 5Y NOTE - CHICAGO BOARD OF TRADE,4,0,50.0,1.54,11.33,1.97,1.68,1.77,461.88
6,NAT GAS NYME - NEW YORK MERCANTILE EXCHANGE,1,0,100.0,1.39,43.36,0.00,0.00,999.00,417.05
7,SOYBEAN MEAL - CHICAGO BOARD OF TRADE,1,0,100.0,0.63,33.21,0.00,0.00,999.00,189.00
8,COCOA - ICE FUTURES U.S.,3,5,33.3,0.61,2.27,1.90,0.02,1.31,183.30
9,LEAN HOGS - CHICAGO MERCANTILE EXCHANGE,2,0,50.0,0.47,0.77,0.29,0.60,2.61,141.07
10,PALLADIUM - NEW YORK MERCANTILE EXCHANGE,1,0,100.0,0.18,5.33,0.00,0.00,999.00,55.50
11,PLATINUM - NEW YORK MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
12,WHEAT-SRW - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
13,VIX FUTURES - CBOE FUTURES EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
14,OATS - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
15,SO AFRICAN RAND - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
16,RUSSELL E-MINI - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
17,MICRO SILVER - COMMODITY EXCHANGE INC.,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
18,SOYBEANS - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
19,SUGAR NO. 11 - ICE FUTURES U.S.,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
20,UST BOND - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
21,UST 10Y NOTE - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
22,UST 2Y NOTE - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
23,SOYBEAN OIL - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
24,AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
25,WTI-PHYSICAL - NEW YORK MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
26,BRITISH POUND - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
27,COFFEE C - ICE FUTURES U.S.,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
28,COPPER- #1 - COMMODITY EXCHANGE INC.,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
29,CORN - CHICAGO BOARD OF TRADE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
30,COTTON NO. 2 - ICE FUTURES U.S.,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
31,E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
32,EMINI RUSSELL 1000 GROWTH - CHICAGO MERCANTILE...,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
33,BRAZILIAN REAL - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
34,FEEDER CATTLE - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
35,GASOLINE RBOB - NEW YORK MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
36,GOLD - COMMODITY EXCHANGE INC.,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
37,JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
38,LIVE CATTLE - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
39,MEXICAN PESO - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
40,MICRO BITCOIN - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
41,MICRO E-MINI NASDAQ-100 INDEX - CHICAGO MERCAN...,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
42,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,0,0,0.0,0.00,0.00,0.00,0.00,0.00,0.00
43,EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTI...,2,0,50.0,-0.20,-3.29,0.99,-0.35,0.80,-60.44
44,MICRO GOLD - COMMODITY EXCHANGE INC.,3,0,0.0,-3.12,-1.24,3.12,-1.25,0.00,-937.01
45,MINI SOYBEANS - CHICAGO BOARD OF TRADE,5,0,0.0,-5.01,-4.45,5.01,-8.12,0.00,-1501.77
46,*** TOTAL ***,32,11,50.0,0.37,6.27,3.46,0.96,2.13,5039.72

In [10]:
from backtest_engine.data import load_cot_data as load_data
from backtest_engine.indicators import calculate_atr
from backtest_engine.cot_rsi import (
    prepare_strategy_data, generate_signals, COTRSIBacktester,
)
import pandas as pd
import plotly.express as px

RSI_EXIT = 60
MA_STOP_MULT = 2
MA_TARGET_MULT = 3
MA_INITIAL = 30_000

holds = [5, 7, 10, 15, 20, 30]
mas = [5, 10, 20, 50, 75, 100, 150, 200]

def MA_backtest_next_open(df, market, hold):
    df = df.copy()
    fill = df["signal"] != 0
    df.loc[fill, "Close"] = df.loc[fill, "Open"]
    bt = COTRSIBacktester(
        initial_capital=MA_INITIAL,
        risk_per_trade=0.01,
        atr_stop_mult=MA_STOP_MULT,
        atr_target_mult=MA_TARGET_MULT,
        max_hold_days=hold,
        rsi_exit=RSI_EXIT,
    )
    return bt.backtest(df, market_name=market)

raw = load_data()
markets = sorted(raw.loc[raw["data_type"] == "daily_price", "Market"].unique())

prepared = {}
for market in markets:
    df = prepare_strategy_data(raw, market)
    if df.empty:
        continue
    df = generate_signals(calculate_atr(df, period=10))
    df["signal_raw"] = df["signal"]
    prepared[market] = df

rows = []
for ma in mas:
    for hold in holds:
        total_pnl = 0.0
        n_trades = 0
        for market, base in prepared.items():
            df = base.copy()
            df["MA"] = df["Close"].rolling(ma).mean()
            df["signal"] = df["signal_raw"]
            df.loc[(df["signal"] == 1) & ~(df["Close"] > df["MA"]), "signal"] = 0
            df.loc[(df["signal"] == -1) & ~(df["Close"] < df["MA"]), "signal"] = 0
            df["signal"] = df["signal"].shift(1).fillna(0).astype(int)

            res = MA_backtest_next_open(df, market, hold)
            if not res["trades"].empty:
                total_pnl += res["trades"]["pnl"].sum()
                n_trades += len(res["trades"])
        rows.append({
            "ma": ma,
            "max_hold_days": hold,
            "net_profit": total_pnl,
            "trades": n_trades,
        })

grid = pd.DataFrame(rows)
pivot = grid.pivot(index="ma", columns="max_hold_days", values="net_profit")
px.imshow(
    pivot,
    text_auto=".0f",
    aspect="auto",
    labels=dict(x="Max hold (days)", y="MA period", color="Net P&L"),
    title="COT+RSI + 1 MA (next-day open) — net P&L",
).show()
grid.sort_values("net_profit", ascending=False).head(10)

     ma  max_hold_days   net_profit  trades
22   50             20  1916.453650      24
23   50             30  1916.453650      24
21   50             15  1863.953650      24
18   50              5  1553.994375      25
20   50             10  1504.664587      24
19   50              7  1368.689775      24
34  100             20  1139.067392      27
35  100             30  1139.067392      27
30  100              5  1106.451397      28
33  100             15  1058.067392      27

#### MA Alerts (50-day MA, next-day open)

In [11]:
from datetime import datetime, timedelta
from IPython.display import display
from backtest_engine.data import load_cot_data as load_data
from backtest_engine.indicators import calculate_atr
from backtest_engine.cot_rsi import prepare_strategy_data, generate_signals
import pandas as pd

ALERT_MA = 50           # heatmap winner
ALERT_LOOKBACK_DAYS = 31
ALERT_N = 4

raw = load_data()
markets = sorted(raw.loc[raw["data_type"] == "daily_price", "Market"].unique())
cutoff = pd.Timestamp(datetime.now() - timedelta(days=ALERT_LOOKBACK_DAYS))

alerts = []

for market in markets:
    df = prepare_strategy_data(raw, market)
    if df.empty or len(df) < ALERT_MA + 2:
        continue
    df = generate_signals(calculate_atr(df, period=10)).reset_index(drop=True)
    df["MA"] = df["Close"].rolling(ALERT_MA).mean()

    df.loc[(df["signal"] == 1) & ~(df["Close"] > df["MA"]), "signal"] = 0
    df.loc[(df["signal"] == -1) & ~(df["Close"] < df["MA"]), "signal"] = 0

    df["entry_date"] = df["Date"].shift(-1)
    df["entry_open"] = df["Open"].shift(-1)

    hit = df[(df["signal"] != 0) & (df["Date"] >= cutoff)]
    for _, row in hit.iterrows():
        pending = pd.isna(row["entry_date"])
        alerts.append({
            "Market": market,
            "Signal date": row["Date"],
            "Entry date": None if pending else row["entry_date"],
            "Fill": "NEXT OPEN (pending)" if pending else "next open",
            "Entry price": None if pending else round(float(row["entry_open"]), 4),
            "Signal": "LONG" if row["signal"] == 1 else "SHORT",
            "Close": round(float(row["Close"]), 4),
            f"MA{ALERT_MA}": round(float(row["MA"]), 4),
            "Commercial_Index": round(float(row["Commercial_Index"]), 1),
            "RSI": round(float(row["RSI"]), 1),
        })

ALERTS = pd.DataFrame(alerts)
print(f"Raw MA{ALERT_MA} alerts in last {ALERT_LOOKBACK_DAYS} days: {len(ALERTS)}")
if not ALERTS.empty:
    ALERTS = ALERTS.sort_values("Signal date", ascending=False).head(ALERT_N)
display(ALERTS)

Raw MA50 alerts in last 31 days: 6

,Market,Signal date,Entry date,Fill,Entry price,Signal,Close,MA50,Commercial_Index,RSI
2,COCOA - ICE FUTURES U.S.,2026-09-16,2026-09-17,next open,5946.0,LONG,5979.0,5830.140,81.9,19.0
1,COCOA - ICE FUTURES U.S.,2026-09-15,2026-09-16,next open,5917.0,LONG,5923.0,5825.440,81.9,11.4
0,COCOA - ICE FUTURES U.S.,2026-09-14,2026-09-15,next open,5980.0,LONG,6023.0,5820.560,81.7,24.1
5,MICRO GOLD - COMMODITY EXCHANGE INC.,2026-09-11,2026-09-14,next open,4374.5,LONG,4408.9,4323.638,100.0,28.3

In [12]:
from backtest_engine.data import load_cot_data

cot = load_cot_data()
g = cot[
    (cot["Market"] == "GOLD - COMMODITY EXCHANGE INC.")
    & (cot["data_type"] == "weekly_cot")
].sort_values("Date")

cols = [c for c in [
    "Date", "Commercial_Index", "Net Commercial Position",
    "Commercial Positions-Long (All)", "Commercial Positions-Short (All)", "OI",
] if c in g.columns]
g[cols].tail(12)

,Date,Commercial_Index,Net Commercial Position,Commercial Positions-Long (All),Commercial Positions-Short (All),OI
9713,2026-06-30,42.741238,-221070.0,59118.0,280188.0,369541.0
9718,2026-07-07,42.304588,-222282.0,59564.0,281846.0,371776.0
9724,2026-07-14,45.004467,-214788.0,79639.0,294427.0,383689.0
9730,2026-07-21,45.576940,-213199.0,80457.0,293656.0,383368.0
9736,2026-07-28,45.897582,-212309.0,75460.0,287769.0,384603.0
9742,2026-08-04,40.788203,-226491.0,71832.0,298323.0,371551.0
9748,2026-08-11,31.367449,-252640.0,69385.0,322025.0,400309.0
9754,2026-08-18,29.285797,-258418.0,69050.0,327468.0,406260.0
9760,2026-08-25,21.659918,-279585.0,62453.0,342038.0,427957.0
9766,2026-09-01,27.016083,-264718.0,61450.0,326168.0,415196.0
9771,2026-09-08,25.014411,-270274.0,54403.0,324677.0,411227.0
9777,2026-09-15,28.095818,-261721.0,56417.0,318138.0,409899.0